### ISSUE TITLE
Please create a user field that allows the FW team to flag users into behaviour categories.

### ISSUE THREAD

**Issue by cwbmuller** [pango-studio/funda.fundawande.org#32]

**Comment by JasonTame** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Please create a user field that allows the FW team to flag users into behaviour categories.](https://trello.com/c/U14qH6zS/394-please-create-a-user-field-that-allows-the-fw-team-to-flag-users-into-behaviour-categories)

**Comment by JasonTame** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Please create a user field that allows the FW team to flag users into behaviour categories.](https://trello.com/c/U14qH6zS/394-please-create-a-user-field-that-allows-the-fw-team-to-flag-users-into-behaviour-categories)
