### ISSUE TITLE
Make module title bold, not module 1

### ISSUE THREAD

**Issue by cwbmuller** [pango-studio/funda.fundawande.org#54]
┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1112859893489994">module title.png</a>

**Comment by JasonTame** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make module title bold, not module 1](https://trello.com/c/Q7B0WYIf/407-make-module-title-bold-not-module-1)
