### ISSUE TITLE
Reverse font sizing and weight on lesson title

### ISSUE THREAD

**Issue by cwbmuller** [pango-studio/funda.fundawande.org#55]
┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1112859893489996">lesson_title.png</a>

**Comment by JasonTame** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Reverse font sizing and weight on lesson title](https://trello.com/c/2JdrLLXC/406-reverse-font-sizing-and-weight-on-lesson-title)
