### ISSUE TITLE
Remove the automatic instructions from all questions

### ISSUE THREAD

**Issue by cwbmuller** [pango-studio/funda.fundawande.org#58]
The content team are adding instructions for each quiz anyway, so it doesn't make sense to duplicate it by having a hard-coded instruction as well

**Comment by JasonTame** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove the automatic instructions from all questions](https://trello.com/c/qIu7ywbs/403-remove-the-automatic-instructions-from-all-questions)
