### ISSUE TITLE
Add table content type

### ISSUE THREAD

**Issue by cwbmuller** [pango-studio/funda.fundawande.org#59]
Although it was previously decided that tables should just be images, there is a need for the table content type again. 

The ACF table plugin is super buggy, so it might be necessary to dig into its code, dig out the important stuff and implement it ourselves.

**Comment by JasonTame** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add table content type](https://trello.com/c/dyQLKflE/402-add-table-content-type)
