### ISSUE TITLE
Multi-line quiz is always marked as incorrect

### ISSUE THREAD

**Issue by cwbmuller** [pango-studio/funda.fundawande.org#61]
If you add a multi-line quiz to a lesson, it is always marked as incorrect and does not allow the learner to submit

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1112859893489992">multi-line submission quiz is always incorrect.png</a>

**Comment by JasonTame** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Multi-line quiz is always marked as incorrect](https://trello.com/c/4GIg8ltq/400-multi-line-quiz-is-always-marked-as-incorrect)
