### ISSUE TITLE
Keep lesson order the same after saving lessons

### ISSUE THREAD

**Issue by cwbmuller** [pango-studio/funda.fundawande.org#62]
The content management team make a lot of small changes to individual lessons. When they save a lesson, it moves to the beginning of a unit. It’s easy enough to go into the Order Lesson screen and move it back, but it gets quite tedious and prone to error if you do that 50 times a day over multiple courses. Ideally, the lesson should remain in the order that it’s in - so if it was lesson 5, it should remain lesson 5 after saving

**Comment by JasonTame** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Keep lesson order the same after saving lessons](https://trello.com/c/YQKY1Lxl/399-keep-lesson-order-the-same-after-saving-lessons)

**Comment by JasonTame** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Keep lesson order the same after saving lessons](https://trello.com/c/YQKY1Lxl/399-keep-lesson-order-the-same-after-saving-lessons)
